name: Build Themis App and Deploy on Firebase
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }} and build
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm run appStartProd

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.5.0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: 1//09snfGLMAbvogCgYIARAAGAkSNwF-L9IrO7Ly1MYVcEmP4YI8yPaQng3TBYDb12PPXfhxm-XLFNZ3ScRE5gIovw5PxpE72bmKdWY
